package com.example.dibujot.gcode

import org.junit.Assert.assertEquals
import org.junit.Test

class GcodeParserTest {

    private val parser = GcodeParser()

    // Scenario: Blanks removed
    @Test
    fun `blank lines are removed`() {
        val input = listOf("G28", "", "  ", "G1 X0")
        val result = parser.parse(input)
        assertEquals(listOf("G28", "G1 X0"), result)
    }

    // Scenario: Comments removed (lines starting with ;)
    @Test
    fun `comment lines are removed`() {
        val input = listOf("; this is a comment", "G28", ";another comment")
        val result = parser.parse(input)
        assertEquals(listOf("G28"), result)
    }

    // Scenario: Inline comments stripped
    @Test
    fun `inline comments are stripped from lines`() {
        val input = listOf("G1 X10 ; move x")
        val result = parser.parse(input)
        assertEquals(listOf("G1 X10"), result)
    }

    // Scenario: Valid commands preserved
    @Test
    fun `valid commands are preserved`() {
        val input = listOf("G28", "G1 X0 Y0", "M104 S200")
        val result = parser.parse(input)
        assertEquals(listOf("G28", "G1 X0 Y0", "M104 S200"), result)
    }

    // Scenario: Empty input
    @Test
    fun `empty input returns empty list`() {
        val result = parser.parse(emptyList())
        assertEquals(listOf<String>(), result)
    }

    // Scenario: Order maintained
    @Test
    fun `valid lines preserve original relative order`() {
        val input = listOf("; start", "G28", "", "G1 X0 Y0", "; home done", "M104 S200")
        val result = parser.parse(input)
        assertEquals(listOf("G28", "G1 X0 Y0", "M104 S200"), result)
    }

    // Triangulation: mixed inline comment + blank + comment-only
    @Test
    fun `complex gcode file is parsed correctly`() {
        val input = listOf(
            "; Generated by Slicer",
            "",
            "G28 ; home all",
            "G1 X10 Y10 F3000 ; move",
            "  ",
            "M104 S200"
        )
        val result = parser.parse(input)
        assertEquals(listOf("G28", "G1 X10 Y10 F3000", "M104 S200"), result)
    }
}
